insert into tb_person (id, first_name, last_name, address, gender) VALUES
    (1, 'Siusan', 'Marney', '8822 Reindahl Place', 'Female'),
    (2, 'Costa', 'Scougall', '5369 Coolidge Parkway', 'Male'),
    (3, 'Nicol', 'Dutteridge', '3 Carioca Court', 'Female'),
    (4, 'Kass', 'Duxbarry', '5 Sunnyside Avenue', 'Female'),
    (5, 'Anitra', 'Mallan', '36002 Duke Plaza', 'Female'),
    (6, 'Carr', 'Dorsett', '649 Grim Way', 'Male'),
    (7, 'Tab', 'Wimbridge', '92284 Namekagon Junction', 'Male'),
    (8, 'Sissie', 'Beddows', '7622 Pierstorff Plaza', 'Polygender'),
    (9, 'Aldon', 'Lasslett', '769 Caliangt Hill', 'Male'),
    (10, 'Tootsie', 'Deverson', '5259 Ruskin Center', 'Female'),
    (11, 'Anna-diana', 'McClary', '1739 Green Ridge Park', 'Female'),
    (12, 'Bennie', 'Laite', '56 Briar Crest Junction', 'Genderfluid'),
    (13, 'Christian', 'Stitson', '23519 Rieder Hill', 'Male'),
    (14, 'Iain', 'Soldi', '0789 Lake View Circle', 'Agender'),
    (15, 'Annabela', 'Raistrick', '00187 Burrows Road', 'Female'),
    (16, 'Blithe', 'Mole', '2994 Messerschmidt Alley', 'Female'),
    (17, 'Orland', 'Antley', '30 Continental Park', 'Male'),
    (18, 'Vail', 'Dunkerly', '28956 West Parkway', 'Polygender'),
    (19, 'Glenda', 'Frugier', '51791 Anhalt Alley', 'Female'),
    (20, 'Paloma', 'Giraudou', '102 Dovetail Trail', 'Female');